apiVersion: apps/v1
kind: Deployment
metadata:
  name: portcullis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portcullis-app
  template:
    metadata:
      labels:
        app: portcullis-app
    spec:
      containers:
      - name: portcullis-app
        image: micwhitehorngillam/castle-portcullis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: gate-web-ui
          containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: portcullis-service
spec:
  type: NodePort
  selector:
    app: portcullis-app
  ports:
  - port: 4000
    protocol: TCP
    targetPort: gate-web-ui
    nodePort: 31000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: castle-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /(.*)
        backend:
          service:
            name: portcullis-service
            port:
              number: 4000
---